# -*- coding: utf-8 -*-
"""Preçoaçõesapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jdWxec8g2RrlCYAwplWK768K_aKn0DBq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests
import datetime as dt

from alpha_vantage.timeseries import TimeSeries

key = 'IDAQDS3JBQW6OXWE'

ts = TimeSeries(key, output_format ='pandas')
data, meta = ts.get_intraday('TSLA', interval='1min', outputsize='full')

data.info()

ts = TimeSeries(key, output_format ='pandas')
dados, meta = ts.get_daily('AAPL', outputsize='full')

dados

plt.plot(dados['4. close'])

dados.info()